env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo

# store our secrets here
    github_token: "ENCRYPTED[!42c5f4329b3ff90c6799039b83d5324e8d9b3be65ca8aabaf619abaa068bc4c84b96782d39b162dafbb60f7399f8f12a!]"
    old_token: "ENCRYPTED[!785dcb23e4ce3848edc93941cb77795e9b847ca9fa7c1cdc18b31d8b824f65abcfb2c602b03fd9bb8023f3258ac00915!]"
    bot_api: "1931889268:AAF-MMVj3-A5c5iUuFAHGrkSkjLsTlthXrs"
    chat_id: -1001579365527
    git_cookies: 0
    REAL_REPO_OWNER: "wHo-EM-i"

# store information about git here
    gmail: buildbot03@gmail.com

task:
    name: Bye
    timeout_in: 120m
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32G
    down_background_script:
      - git clone https://$CIRRUS_REPO_OWNER:$old_token@github.com/projects-nexus/ci-script /tmp/cs
      - mv /tmp/cs/* /tmp/ci
      - bash down*
    symc_script:
      - bash sy*
    compile_script:
      - bash bu*
    upl_script:
      - bash upl*
