#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

SECONDS=0

if [[ $git_cookies != 0 ]]; then

sudo touch /etc/mtab
sudo chmod 777 /etc/mtab

echo "$git_cookies" > ~/git_cookies.sh
bash ~/git_cookies.sh

fi

# Sync source
repo init --depth=1 --no-repo-verify -u https://github.com/xdroid-oss/xd_manifest -b thirteen -g default,-mips,-darwin,-notdefault

# Sync source without unnecessary messages, try with -j30 first, if fails, it will try again
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

# local manifest
git clone --depth=1 https://ImSpiDy:$my_og_token@github.com/wHo-EM-i/device_xiaomi_lavender -b xd device/xiaomi/lavender
git clone --depth=1 https://github.com/wHo-EM-i/android_vendor_xiaomi_lavender -b T vendor/xiaomi/lavender
git clone --depth=1 https://ImSpiDy:$my_og_token@github.com/ImSpiDy/Xtreme_Kernel -b xd-1 kernel/xiaomi/lavender
git clone --depth=1 https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r433403b.git -b 12.0 prebuilts/clang/host/linux-x86/clang-dora
rm -rf hardware/qcom-caf/msm8998/audio hardware/qcom-caf/msm8998/media hardware/qcom-caf/msm8998/display
git clone -b 8998-4.4 https://github.com/wHo-EM-i/android_hardware_qcom_audio hardware/qcom-caf/msm8998/audio
git clone -b 8998-4.4 https://github.com/wHo-EM-i/android_hardware_qcom_display hardware/qcom-caf/msm8998/display
git clone -b 8998-4.4 https://github.com/wHo-EM-i/android_hardware_qcom_media hardware/qcom-caf/msm8998/media

. /tmp/ci/function
tg "$rom_name source sync completed!
Total Size: $(du -sh /tmp/rom | cut -d - -f 1 | cut -d / -f 1)
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress"

echo "$(($SECONDS / 60))" > /tmp/sync_time.txt
