#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom
. /tmp/ci/function

SECONDS=0

if [[ $git_cookies != 0 ]]; then

sudo touch /etc/mtab
sudo chmod 777 /etc/mtab

echo "$git_cookies" > ~/git_cookies.sh
bash ~/git_cookies.sh

fi

# Initialise Local Repository and Sync
repo init --depth=1 -u https://github.com/crdroidandroid/android.git -b 11.0 -g default,-mips,-darwin,-notdefault

repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

# Clone DT, VT, KT
git clone --depth=1 https://reaPeR1010:$old_token@github.com/reaPeR1010/android_device_motorola_sanders device/motorola/sanders -b 11
git clone --depth=1 https://reaPeR1010:$old_token@github.com/reaPeR1010/android_vendor_motorola_sanders vendor/motorola/sanders -b 11
git clone --depth=1 https://reaPeR1010:$old_token@github.com/reaPeR1010/android_kernel_motorola_sanders kernel/motorola/msm8953

# Get LOS Hals
rm -rf hardware/qcom-caf/msm8996/display
rm -rf hardware/qcom-caf/msm8996/audio
rm -rf hardware/qcom-caf/msm8996/media
git clone --depth=1 https://github.com/LineageOS/android_hardware_qcom_display hardware/qcom-caf/msm8996/display -b lineage-18.1-caf-msm8996
git clone --depth=1 https://github.com/LineageOS/android_hardware_qcom_audio hardware/qcom-caf/msm8996/audio -b lineage-18.1-caf-msm8996
git clone --depth=1 https://github.com/LineageOS/android_hardware_qcom_media hardware/qcom-caf/msm8996/media -b lineage-18.1-caf-msm8996

tg "$rom_name source sync completed!
Total Size: $(du -sh /tmp/rom | cut -d - -f 1 | cut -d / -f 1)
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress"

echo "$(($SECONDS / 60))" > /tmp/sync_time.txt
